# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'airbnb'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'airbnb'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]  # Tables and views we are building
analysis-paths: ["analyses"] # sls we need to execute manually
test-paths: ["tests"] # data tests to ensure data quality
seed-paths: ["seeds"] # CSV files we load into the data warehouse - like local data
macro-paths: ["macros"] # reusable snippets of SQL code
snapshot-paths: ["snapshots"] # point-in-time copies of records - useful for slowly changing dimensions
asset-paths: ["assets"] # non-SQL files to be included in the project

clean-targets:         # directories to be removed by `dbt clean` # to get rid of compiled files
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
on-run-start:
  - "CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log ( model_name STRING, run_timestamp TIMESTAMP )"

models: # for modfels in the models/ directory - or model defined in the model-paths
  airbnb:
  